# Generated by Django 4.0.5 on 2022-06-30 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_message_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='desc',
            new_name='description',
        ),
    ]
